mean(mtcars$mpg)
example <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 4, ncol = 2)
View(example)
View(mtcars)
setwd("~/")
install.packages(c("ggplot2", "devtools", "lme4"))
library(c("ggplot2", "devtools", "lme4"))
source("https://bioconductor.org/biocLite.R")
biocLite("GenomicFeatures")
BiocManager::("GenomicFeatures")
BiocManager::"GenomicFeatures"
BiocManager("GenomicFeatures")
BiocManager::install()
install_github("author/package")
library(devtools)
?devtools
detach("package:devtools", unload=TRUE)
library("devtools", lib.loc="/Library/Frameworks/R.framework/Versions/3.6/Resources/library")
detach("package:devtools", unload=TRUE)
library("devtools", lib.loc="/Library/Frameworks/R.framework/Versions/3.6/Resources/library")
detach("package:devtools", unload=TRUE)
library("devtools", lib.loc="/Library/Frameworks/R.framework/Versions/3.6/Resources/library")
installed.packages()
library()
version
sessionInfo
library(devtools)
version(devtools)
version("devtools")
version(package:"devtools")
help(ggplot2)
help("ggplot2")
help(package:"ggplot2")
help(package="ggplot2")
help(package="devtools")
version(package="devtools")
browseVignettes("ggplot2")
browseVignettes("devtools")
?devtools
help(package=devtools)
help(package=devtools)
help(package="devtools")
install.packages("KernSmooth")
library(KernSmooth)
version(KernSmooth)
?devtools
help(package="devtools")
browseVignettes("devtools")

install.packages("rmarkdown")
